config/routes.rb
Rails.application.routes.draw do
  resources :nikkis
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :nikkis
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/nikki.rb
class Nikki < ApplicationRecord
	validates :title, presence: true, length: { maximum: 255 }
	validates :body, presence: true, length: { maximum: 10_000 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/nikkis_controller.rb
class NikkisController < ApplicationController
  before_action :set_nikki, only: [:show, :edit, :update, :destroy]

  # GET /nikkis
  # GET /nikkis.json
  def index
    @nikkis = Nikki.all
  end

  # GET /nikkis/1
  # GET /nikkis/1.json
  def show
  end

  # GET /nikkis/new
  def new
    @nikki = Nikki.new
  end

  # GET /nikkis/1/edit
  def edit
  end

  # POST /nikkis
  # POST /nikkis.json
  def create
    @nikki = Nikki.new(nikki_params)

    respond_to do |format|
      if @nikki.save
        format.html { redirect_to @nikki, notice: 'Nikki was successfully created.' }
        format.json { render :show, status: :created, location: @nikki }
      else
        format.html { render :new }
        format.json { render json: @nikki.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nikkis/1
  # PATCH/PUT /nikkis/1.json
  def update
    respond_to do |format|
      if @nikki.update(nikki_params)
        format.html { redirect_to @nikki, notice: 'Nikki was successfully updated.' }
        format.json { render :show, status: :ok, location: @nikki }
      else
        format.html { render :edit }
        format.json { render json: @nikki.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nikkis/1
  # DELETE /nikkis/1.json
  def destroy
    @nikki.destroy
    respond_to do |format|
      format.html { redirect_to nikkis_url, notice: 'Nikki was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nikki
      @nikki = Nikki.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nikki_params
      params.require(:nikki).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nikkis_helper.rb
module NikkisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      ヘッダー
    </header><!-- /header -->
    <%= yield %>
    <footer>
      フッター
    </footer>
  </body>
</html>

app/views/nikkis/_form.html.erb
<%= form_with(model: nikki, local: true) do |form| %>
  <% if nikki.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nikki.errors.count, "error") %> prohibited this nikki from being saved:</h2>

      <ul>
      <% nikki.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nikkis/edit.html.erb
<h1>Editing Nikki</h1>

<%= render 'form', nikki: @nikki %>

<%= link_to 'Show', @nikki %> |
<%= link_to 'Back', nikkis_path %>

app/views/nikkis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nikkis</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>投稿日時</th>
      <th>更新日時</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nikkis.each do |nikki| %>
      <tr>
        <td><%= nikki.id %></td>
        <td><%= link_to nikki.title, nikki %></td>
        <td><%= nikki.created_at %></td>
        <td><%= nikki.updated_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '日記を新規作成', new_nikki_path %>

app/views/nikkis/new.html.erb
<h1>New Diary</h1>

<%= render 'form', nikki: @nikki %>

<%= link_to 'Back', nikkis_path %>

app/views/nikkis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @nikki.id %>
</p>

<p>
  <strong>タイトル:</strong>
  <%= @nikki.title %>
</p>
<p>
  <strong>本文:</strong>
  <%= @nikki.body %>
</p>
<p>
  <strong>登録日時:</strong>
  <%= @nikki.created_at %>
</p>
<p>
  <strong>更新日時:</strong>
  <%= @nikki.updated_at %>
</p>

<%= link_to '編集', edit_nikki_path(@nikki) %> |
<%= link_to '削除', @nikki, method: :delete, data: { confirm: '本当に削除しますか？'} %> |
<%= link_to '一覧に戻る', nikkis_path %>